logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8181
spring:
  datasource:
    url: @dataSource.url@
    username: @dataSource.user@
    password: @dataSource.password@
    dbcp2:
      max-total: 4
      max-idle: 2
      max-wait-millis: 10000
      remove-abandoned-on-borrow: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      validation-query: SELECT 1
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "http://localhost:8080/realms/OurKnowledge"
          jwk-set-uri: " ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs"

jwt:
  auth:
    converter:
      resource-id: "ourknowledge-client"
      principle-attribute: "preferred_username"